version: '3.8'


services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017

  # ddd-typescript-example:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # environment:
  #   #   ENV_NAME: dev
  #   ports:
  #     - 5000:5000
  